Repository godot-rust/gdnative, pull requests merged in 2019-09, with the labels that each got.

#198 fix warnings
  bindings_generator/src/methods.rs
  bindings_generator/src/special_methods.rs
  examples/scene_create/src/lib.rs
  gdnative-bindings/src/lib.rs
  gdnative-core/src/access.rs
  gdnative-core/src/byte_array.rs
  gdnative-core/src/class.rs
  gdnative-core/src/color_array.rs
  gdnative-core/src/dictionary.rs
  gdnative-core/src/float32_array.rs
  gdnative-core/src/generated.rs
  gdnative-core/src/init.rs
  gdnative-core/src/int32_array.rs
  gdnative-core/src/lib.rs
  gdnative-core/src/macros.rs
  gdnative-core/src/node_path.rs
  gdnative-core/src/string.rs
  gdnative-core/src/string_array.rs
  gdnative-core/src/user_data.rs
  gdnative-core/src/variant.rs
  gdnative-core/src/variant_array.rs
  gdnative-core/src/vector2.rs
  gdnative-core/src/vector2_array.rs
  gdnative-core/src/vector3.rs
  gdnative-core/src/vector3_array.rs
  gdnative-derive/src/derive_conv_variant.rs
  gdnative-derive/src/derive_macro.rs
  gdnative-derive/src/lib.rs
  test/src/lib.rs
Labels: bindings-generator, bug

#199 check formatting in CI
  .travis.yml
Labels: enhancement

#201 implement ToString for GodotString
  gdnative-core/src/string.rs
Labels: enhancement

#203 implement Hash for GodotString
  gdnative-core/src/string.rs
Labels: core-wrappers, enhancement

#210 fix vararg-method return types
  bindings_generator/src/methods.rs
  gdnative-sys/src/api.rs
Labels: bindings-generator, bug

#213 Support Instance downcasting with NativeScript 1.1 type tags
  gdnative-core/src/class.rs
  gdnative-core/src/init.rs
  gdnative-core/src/lib.rs
  gdnative-core/src/macros.rs
  gdnative-core/src/type_tag.rs
  test/src/lib.rs
Labels: enhancement

#219 disable cache on CI, remove some dependencies
  .travis.yml
  gdnative-sys/Cargo.toml
Labels: enhancement
