Repository godot-rust/gdnative, pull requests merged in 2020-02, with the labels that each got.

#287 Update changelog with unreleased changes since 0.7.0
  CHANGELOG.md
Labels: documentation

#292 Always generate Drop for reference counted types
  bindings_generator/src/lib.rs
Labels: bindings-generator, bug

#286 Add workaround for iOS build
  gdnative-sys/build.rs
Labels: bug

#293 Fix leaks from reference-counted types in return position
  bindings_generator/src/methods.rs
  bindings_generator/src/special_methods.rs
  gdnative-core/src/object.rs
  test/src/lib.rs
  test/src/test_derive.rs
  test/src/test_free_ub.rs
  test/src/test_register.rs
  test/src/test_return_leak.rs
  test/src/test_variant_call_args.rs
Labels: bindings-generator, bug

#298 Assorted fixes for gdnative-sys
  gdnative-sys/build.rs
  gdnative-sys/src/lib.rs
Labels: bug

#299 Add cargo test CI jobs on Windows
  .travis.yml
  gdnative-sys/build.rs
Labels: enhancement

#306 Update user_data.rs
  gdnative-core/src/user_data.rs
Labels: documentation
