Repository godot-rust/gdnative, pull requests merged in 2020-07, with the labels that each got.

#513 Fix the one_class_one_file feature flag.
  gdnative-bindings/build.rs
  gdnative/Cargo.toml
Labels: bug

#514 Implement ThreadLocal state for Variant collections
  gdnative-core/src/core_types/dictionary.rs
  gdnative-core/src/core_types/variant_array.rs
  impl/proc_macros/Cargo.toml
  impl/proc_macros/src/doc.rs
  impl/proc_macros/src/lib.rs
Labels: core-wrappers, enhancement

#517 Fix type mismatch on Windows, add MSVC target to CI
  .travis.yml
  gdnative-core/src/private.rs
Labels: bug

#520 Fix doc comment on GodotObject::cast
  gdnative-core/src/object.rs
Labels: documentation

#522 Add the godot_init convenience macro
  README.md
  examples/dodge_the_creeps/src/lib.rs
  examples/hello_world/src/lib.rs
  examples/scene_create/src/lib.rs
  examples/signals/src/lib.rs
  examples/spinning_cube/src/lib.rs
  gdnative-core/src/nativescript/init.rs
  gdnative-core/src/nativescript/macros.rs
  gdnative/src/lib.rs
  gdnative/src/prelude.rs
  test/src/lib.rs
Labels: enhancement

#523 Bump euclid version to 0.20.13
  examples/scene_create/Cargo.toml
  gdnative-core/Cargo.toml
Labels: bug

#530 [529] Adding `NewRef` to `prelude`
  gdnative/src/prelude.rs
Labels: core-wrappers, enhancement

#535 Re-export `ToVariantEq` and `FromVariantError` in the prelude
  gdnative/src/prelude.rs
Labels: enhancement

#537 Add workaround for a rustc bug (rust/43081)
  gdnative-derive/src/methods.rs
Labels: bug, procedural-macro

#536 Derive everything for marker types
  gdnative-core/src/ref_kind.rs
  gdnative-core/src/thread_access.rs
Labels: enhancement

#534 Allow constructors to take owner as TRef
  gdnative-core/src/nativescript/class.rs
  gdnative-core/src/nativescript/init.rs
  gdnative-core/src/nativescript/init/property/accessor.rs
  gdnative-core/src/object.rs
  gdnative-derive/src/native_script.rs
  test/src/lib.rs
  test/src/test_free_ub.rs
  test/src/test_register.rs
  test/src/test_return_leak.rs
  test/src/test_variant_call_args.rs
Labels: breaking-change, enhancement, procedural-macro

#543 List godot-pong-rust as updated for v0.9
  README.md
Labels: documentation

#549 Re-export TypedArray in the prelude
  gdnative/src/prelude.rs
Labels: enhancement

#548 Add RefInstance::claim
  gdnative-core/src/nativescript/class.rs
Labels: enhancement

#553 Remove From implementations on Variant
  gdnative-core/src/core_types/string.rs
  gdnative-core/src/core_types/variant.rs
Labels: breaking-change, core-wrappers
