Repository godot-rust/gdnative, pull requests merged in 2020-08, with the labels that each got.

#556 Fix link to "using custom builds of Godot"
  README.md
Labels: documentation

#551 Implementing Display for user_data errors.
  gdnative-core/src/nativescript/user_data.rs
Labels: enhancement

#561 Implement Display for GodotError
  gdnative-core/src/core_types/error.rs
Labels: enhancement

#565 Fix incorrect references to Rid arguments in ptrcall
  gdnative-core/src/core_types/rid.rs
Labels: bindings-generator, bug

#567 Added Vector2 move_towards function
  gdnative-core/Cargo.toml
  gdnative-core/src/core_types/vector2.rs
Labels: core-wrappers, enhancement

#570 Add get_basename and get_extension to GodotString
  gdnative-core/src/core_types/string.rs
Labels: core-wrappers, enhancement

#573 Minimal integration of profiling api
  gdnative-core/src/nativescript/mod.rs
  gdnative-core/src/nativescript/profiling.rs
Labels: core-wrappers, enhancement
