Repository godot-rust/gdnative, pull requests merged in 2021-02, with the labels that each got.

#686 Fix bounds in RefKindSpec trait
  .github/workflows/ci.yml
  CHANGELOG.md
  gdnative-core/src/object.rs
Labels: bug

#639 Add Array typehints
  Cargo.toml
  examples/array_export/Cargo.toml
  examples/array_export/ExportsArrays.gdns
  examples/array_export/ExportsArrays.tscn
  examples/array_export/array_export_library.gdnlib
  examples/array_export/default_env.tres
  examples/array_export/icon.png
  examples/array_export/icon.png.import
  examples/array_export/project.godot
  examples/array_export/src/lib.rs
  gdnative-core/src/nativescript/init/property.rs
  gdnative-core/src/nativescript/init/property/hint.rs
Labels: breaking-change, enhancement

#681 Unwrangling the mess that is `godot_wrap_method`, adding generic method support as a side effect
  gdnative-core/src/lib.rs
  gdnative-core/src/log.rs
  gdnative-core/src/macros.rs
  gdnative-core/src/nativescript/init.rs
  gdnative-core/src/nativescript/init/method.rs
  gdnative-core/src/nativescript/macros.rs
  gdnative-derive/src/extend_bounds.rs
  gdnative-derive/src/lib.rs
  gdnative-derive/src/methods.rs
  gdnative-derive/src/varargs.rs
  gdnative-derive/src/variant/bounds.rs
  gdnative/src/prelude.rs
  test/Cargo.toml
  test/project/main.gd
  test/src/test_register.rs
Labels: breaking-change, enhancement, procedural-macro

#690 Use a private uninhabited type for Export impls without hints
  gdnative-core/src/nativescript/init/property.rs
Labels: breaking-change, enhancement

#693 Add the MapOwned trait and the `Once<T>` userdata type
  gdnative-core/Cargo.toml
  gdnative-core/src/nativescript/class.rs
  gdnative-core/src/nativescript/macros.rs
  gdnative-core/src/nativescript/mod.rs
  gdnative-core/src/nativescript/user_data.rs
  test/src/lib.rs
  test/src/test_map_owned.rs
Labels: enhancement
