Repository godot-rust/gdnative, pull requests merged in 2021-03, with the labels that each got.

#704 Mention 'header not found' errors in README
  README.md
Labels: documentation

#707 fixing documentation example
  gdnative-core/src/nativescript/init.rs
Labels: dependencies

#711 Add VariantArray duplicate method for deep copy
  gdnative-core/src/core_types/variant_array.rs
Labels: core-wrappers, enhancement
