Repository godot-rust/gdnative, pull requests merged in 2022-10, with the labels that each got.

#952 Fix bug in Vector2::rotated()
  CHANGELOG.md
  gdnative-core/src/core_types/vector2.rs
  gdnative/tests/ui/derive_fail_methods_missing_new.stderr
Labels: bug, c: core

#930 Deprecate Transform2D::from_rotation_translation_scale and add from_scale_rotation_origin
  gdnative-core/src/core_types/geom/transform2d.rs
Labels: bug, c: core

#953 Prepare 0.10.2 release
  CHANGELOG.md
  README.md
  bindings-generator/Cargo.toml
  gdnative-async/Cargo.toml
  gdnative-bindings/Cargo.toml
  gdnative-core/Cargo.toml
  gdnative-derive/Cargo.toml
  gdnative-sys/Cargo.toml
  gdnative/Cargo.toml
  impl/proc-macros/Cargo.toml
Labels: feature

#954 `godot_init` may not find some symbols
  gdnative-core/src/init/macros.rs
Labels: bug

#955 Remove deprecated symbols; rename `NativeClass` derived methods
  gdnative-async/src/rt/bridge.rs
  gdnative-async/src/rt/func_state.rs
  gdnative-core/src/export/class.rs
  gdnative-core/src/init/init_handle.rs
  gdnative-derive/src/lib.rs
  gdnative-derive/src/methods.rs
  gdnative-derive/src/native_script/mod.rs
  gdnative/src/prelude.rs
  test/src/test_register.rs
  test/src/test_return_leak.rs
  test/src/test_variant_call_args.rs
Labels: c: core, c: export, breaking-change, quality-of-life

#961 Fixed ToVariant/FromVariant derive for generic types with bounds
  gdnative-derive/src/variant/bounds.rs
  gdnative-derive/src/variant/from.rs
  gdnative-derive/src/variant/to.rs
  test/src/test_derive.rs
Labels: bug, c: export

#962 allow deriving of `FromVariant` for uninhabitable enums
  gdnative-derive/src/variant/from.rs
  gdnative-derive/src/variant/mod.rs
  test/src/test_derive.rs
Labels: feature, c: export

#966 fix(check.sh): make it more portable
  check.sh
Labels: bug, c: tools

#960 Improve panic messages in init/terminate callbacks
  gdnative-core/src/export/method.rs
  gdnative-core/src/export/property/accessor.rs
  gdnative-core/src/init/init_handle.rs
  gdnative-core/src/init/macros.rs
  gdnative-core/src/private.rs
Labels: bug, c: core

#898 Adding Transform3D operations - fixes issues/290
  gdnative-core/src/core_types/geom/basis.rs
  gdnative-core/src/core_types/geom/transform.rs
Labels: feature, c: core

#964 Derive stringly and numeric ToVariant for fieldless enums
  gdnative-derive/src/native_script/mod.rs
  gdnative-derive/src/variant/attr.rs
  gdnative-derive/src/variant/attr/field.rs
  gdnative-derive/src/variant/attr/item.rs
  gdnative-derive/src/variant/bounds.rs
  gdnative-derive/src/variant/from.rs
  gdnative-derive/src/variant/mod.rs
  gdnative-derive/src/variant/repr.rs
  gdnative-derive/src/variant/to.rs
  gdnative/tests/ui.rs
  gdnative/tests/ui/from_variant_fail_08.rs
  gdnative/tests/ui/from_variant_fail_08.stderr
  gdnative/tests/ui/from_variant_fail_09.rs
  gdnative/tests/ui/from_variant_fail_09.stderr
  gdnative/tests/ui/to_variant_fail_08.rs
  gdnative/tests/ui/to_variant_fail_08.stderr
  gdnative/tests/ui/to_variant_fail_09.rs
  gdnative/tests/ui/to_variant_fail_09.stderr
  test/src/test_derive.rs
Labels: feature, c: export

#969 CI: replace unmaintained actions-rs toolchain with manual installation
  .github/composite/rust/action.yml
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
Labels: c: ci, quality-of-life

#971 Add docs for the `#[variant(enum)]` attribute.
  gdnative-core/src/core_types/variant.rs
Labels: c: export, documentation

#970 Generate accessor methods for indexed properties
  bindings-generator/src/class_docs.rs
  bindings-generator/src/methods.rs
  test/src/lib.rs
  test/src/test_indexed_props.rs
Labels: feature, c: bindings
