Repository godot-rust/gdnative, pull requests merged in 2022-08, with the labels that each got.

#920 Update Android NDK (21 -> 25), workaround Rust bug
  .github/workflows/full-ci.yml
Labels: bug, c: tools

#919 Clippy nightly fixes
  examples/dodge-the-creeps/src/main_scene.rs
  examples/resource/src/lib.rs
  examples/scene-create/src/lib.rs
  gdnative-core/src/core_types/string.rs
  gdnative-core/src/export/method.rs
  gdnative-core/src/export/user_data.rs
  test/src/lib.rs
  test/src/test_derive.rs
Labels: quality-of-life

#921 GitHub Action updates
  .github/composite/godot/action.yml
  .github/composite/llvm/action.yml
  .github/composite/rust/action.yml
  .github/workflows/doc.yml
  .github/workflows/full-ci.yml
  .github/workflows/minimal-ci.yml
  .github/workflows/release-version.yml
  gdnative-core/src/export/macros.rs
Labels: c: ci, quality-of-life

#922 Some refactoring about `gdnative-derive`
  gdnative-derive/src/native_script/mod.rs
  gdnative-derive/src/native_script/property_args.rs
  gdnative-derive/src/variant/mod.rs
Labels: quality-of-life

#925 fix leaks in as_arg tests
  gdnative-core/src/core_types/variant_array.rs
  test/src/test_as_arg.rs
Labels: bug

#934 Automatically detect latest installed Android NDK
  .github/workflows/full-ci.yml
Labels: bug, c: ci

#933 Rename `#[godot]` to `#[method]`
  examples/dodge-the-creeps/src/hud.rs
  examples/dodge-the-creeps/src/main_scene.rs
  examples/dodge-the-creeps/src/mob.rs
  examples/dodge-the-creeps/src/player.rs
  examples/hello-world/src/lib.rs
  examples/native-plugin/src/lib.rs
  examples/resource/src/lib.rs
  examples/rpc/src/client.rs
  examples/rpc/src/server.rs
  examples/scene-create/src/lib.rs
  examples/signals/src/lib.rs
  examples/spinning-cube/src/lib.rs
  gdnative-core/src/export/macros.rs
  gdnative-derive/src/lib.rs
  gdnative-derive/src/methods.rs
  gdnative/tests/ui/derive_pass.rs
  test/src/test_derive.rs
Labels: c: export, breaking-change, quality-of-life

#935 Rename a few remaining occurrences of #[export]
  .github/workflows/full-ci.yml
  README.md
  examples/property-export/src/lib.rs
  gdnative/tests/ui/derive_fail_methods.rs
  gdnative/tests/ui/derive_fail_methods.stderr
  test/src/lib.rs
  test/src/test_async.rs
  test/src/test_derive.rs
  test/src/test_free_ub.rs
  test/src/test_map_owned.rs
  test/src/test_register.rs
  test/src/test_variant_call_args.rs
Labels: c: export, quality-of-life

#936 Fix VariantArray iterator skip logic
  gdnative-core/src/core_types/variant_array.rs
Labels: bug, c: core
