Repository godot-rust/gdnative, pull requests merged in 2022-09, with the labels that each got.

#939 New Color constructors from HTML string and integers
  gdnative-core/src/core_types/color.rs
Labels: feature, c: core

#940 added load function to globalscope
  gdnative/src/gdscript.rs
  gdnative/src/lib.rs
Labels: feature, c: core

#944 Support iOS Simulator on M1 Mac (aarch64-apple-ios-sim)
  gdnative-sys/build.rs
Labels: feature, c: sys, c: tools

#929 Give `get_api` panic message
  gdnative-core/src/macros.rs
  gdnative-core/src/private.rs
Labels: c: tools, quality-of-life

#948 fix(rect2): match Rect2.intersects with Godot logic
  gdnative-core/src/core_types/geom/rect2.rs
Labels: bug
